### ISSUE TITLE
InfoManager xls export encodes a leading prime which isn't an apostrophe

### ISSUE THREAD

**Issue by SvetDE** [CDCgov/erhms-info-manager#4]
- Exported a form from InfoManager using Analysis-Classic, into older version of Excel (driver for newer Excel not loaded on the computer in use) using  WRITE REPLACE "Epi7" {Provider=Microsoft.Jet.OLEDB.4.0;Data Source="myfilepath\myfile.xls";Extended Properties="Excel 8.0;HDR=Yes;"} : [export] *
- Output generated what looked like a leading prime for every single cell in Excel, which wasn't an "apostrophe". Search and replace for an "apostrophe" in Excel didn't work to remove the character. SAS substring function didn't recognize it as an "apostrophe" and when substringing, left a leading blank. Saving xls to xlsx didn't get rid of the character. Copy/paste as text removed the character. Also saving xls to csv to xlxs worked.  
- Export using WRITE REPLACE "Epi7" {Provider=Microsoft.ACE.OLEDB.12.0;Data Source="myfilepath\myfile.xlsx";Extended Properties="Excel 12.0 Xml;HDR=YES"} : [export] *  does not create the leading prime character, however this export may not be an option for all team members.
- What is that character, what is its encoding? Why does it get created? How to avoid this issue in the future?

**Comment by smailliwcs** [comment]
This is something Excel does to force values to be treated as text, usually to avoid automatic type coercion or reformatting.  For instance, if you type `1/2` into a cell, it will get converted to a date representing January 2nd of the current year.  That might be what you intended, but if you actually wanted the value to be "a textual representation of the fraction one-half," you can instead type `'1/2`, which will tell Excel to leave it alone.  (But note you won't be able to work with the value as a number ... as far as Excel knows, it's just a three-character string.  And there are other ways around this, such as formatting the cell as text before entering the value, but sometimes you don't have that option.)

So that character *is* an apostrophe, but it isn't really "there."  At least, Excel should automatically remove it any time you interact with the value itself.  (Let me know if you run into cases where Excel actually reports the first character as an apostrophe.)  Looking at the [Epi Info documentation](https://www.cdc.gov/epiinfo/user-guide/classic-analysis/managedata.html), I don't see a way to control or disable this behavior.  But there are [multiple ways to remove leading apostrophes](https://www.extendoffice.com/documents/excel/2868-excel-remove-leading-apostrophe.html) once they make their way into a worksheet.  The "Text to Columns" option described there might be most appropriate for your situation.
